memoit/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.start, name='start'),
    path('home', views.homepage, name='homepage'),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("account/", views.account, name="account"),
    path("help/", views.help, name="help"),
    path('create/<note_type>', views.create_note, name='createNote'),
    path('delete/<redirect_type>/<note_type>/<note_id>', views.delete_note, name='deleteNote'),
    path('update/<redirect_type>/<note_type>/<note_id>', views.update_note, name='updateNote'),
    path('delete_account/', views.delete_account, name='deleteAccount'),
    path('delete_all/', views.delete_all, name='deleteAll'),
]

memoit/memoit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('secure_admin_changed/', admin.site.urls),
                  path('', include('main.urls')),
                  path('', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memoit/main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
import uuid
from .choices import *
from .other import upload_path_handler


# base note model
class Note(models.Model):
    type = models.IntegerField(default=1, editable=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, default="Default title")
    published = models.DateTimeField('date published', default=datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    content = models.CharField(max_length=3000, blank=True)
    theme = models.IntegerField(default=1, choices=THEMES)

    # override name in Admin page
    class Meta:
        verbose_name_plural = "Notes"

    def __str__(self):
        return self.title


# model for list note
class NoteList(models.Model):
    type = models.IntegerField(default=2, editable=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, default="Default title")
    published = models.DateTimeField('date published', default=datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    content = models.TextField(blank=True)  # json parser to list
    theme = models.IntegerField(default=1, choices=THEMES)

    # override name in Admin page
    class Meta:
        verbose_name_plural = "Notes (list)"

    def __str__(self):
        return self.title


# model for note with picture
class NotePicture(models.Model):
    type = models.IntegerField(default=3, editable=False)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, default="Default title")
    published = models.DateTimeField('date published', default=datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    content = models.CharField(max_length=3000, blank=True)

    # picture is stored in user folder as raw, in model there is information to hashed path of picture
    picture = models.ImageField(upload_to=upload_path_handler, default='main/media/pics_uploaded/none.png', blank=True)

    # override name in Admin page
    class Meta:
        verbose_name_plural = "Notes (picture)"

    def __str__(self):
        return self.title

memoit/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .choices import *
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ValidationError


# override basic authentication form to allow logging in with email or username
class EmailAuthenticationForm(AuthenticationForm):
    def clean_username(self):
        username = self.data['username']
        if '@' in username:
            try:
                username = User.objects.get(email=username).username
            except ObjectDoesNotExist:
                raise ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
        return username


# override basic user creation for to add required email field
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        if commit:
            user.save()
        return user


# form for creating basic text note
class NoteForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(
        widget=forms.Textarea(attrs={'width': "100%", 'cols': "80", 'rows': "20", 'height': '100%'}), required=False)
    theme = forms.ChoiceField(choices=THEMES, label="Theme", initial='', widget=forms.Select(), required=True)


# form for creating list note
class NoteListForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(required=False, label="List items",
                              widget=forms.TextInput(attrs={'placeholder': 'Add item and press Enter'}))
    theme = forms.ChoiceField(choices=THEMES, label="Theme", initial='', widget=forms.Select(), required=True)


# form for creating picture note
class NotePictureForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(
        widget=forms.Textarea(attrs={'width': "100%", 'cols': "80", 'rows': "20", 'height': '100%'}), required=False)
    picture = forms.ImageField()


# override picture note form to show actual picture path
class NotePictureFormUpdate(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(
        widget=forms.Textarea(attrs={'width': "100%", 'cols': "80", 'rows': "20", 'height': '100%'}),
        required=False)
    picture = forms.ImageField(required=False)

memoit/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import *
from .models import *
import os
from memoit.settings import BASE_DIR, MEDIA_ROOT
from django.utils.html import strip_tags
from datetime import datetime
from django.utils.timezone import make_aware
import shutil
from main.emails.emails import welcome_email


# start page view (logo), this shows when user is not logged in
def start(request):
    if request.user.is_authenticated:
        return redirect('main:homepage')
    return render(request, 'main/start.html')


# main desktop view of app, it shows all notes of logged user sorted by modified/created date
def homepage(request):
    # if user is authenticated - collect all of notes from database and sort them by date
    if request.user.is_authenticated:
        notes = [x for x in Note.objects.all() if x.author.username == request.user.username]
        notes_list = [x for x in NoteList.objects.all() if x.author.username == request.user.username]
        list_items = {}
        for item in notes_list:
            list_items[item.id] = item.content.split('|')
        notes_picture = [x for x in NotePicture.objects.all() if x.author.username == request.user.username]
        notes_all = [*notes, *notes_list, *notes_picture]
        notes_all.sort(key=lambda x: x.published, reverse=True)
        # if user don't have any notes, show a message
        if len(notes_all) == 0:
            messages.info(request, 'You don\'t have any notes, create one!')
        # render view by passing dict with all notes to template
        return render(request, 'main/home.html', context={'NotesAll': notes_all,
                                                          'list_items': list_items})

    # if user force to go to desktop view but is not logged in it redirects to start page and show info message
    else:
        messages.info(request, 'You need to log in to access your memos')
        return redirect('main:login')


# register page, checks if username or email exists already in a database
def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                messages.error(request, f'Email {email} is taken')
                return redirect('main:register')
            # if there is unique user, it creates an entry in database and create unique folder to store images
            user = form.save()
            path_temp = os.path.join(os.path.join('main', 'media', 'pics_uploaded'), '')
            path = os.path.join(BASE_DIR, '') + path_temp + username
            if not os.path.isdir(path):
                os.mkdir(path)
            # after success in registering - log in user and redirect to homepage
            messages.success(request, f'New Account created: {username}')
            messages.info(request, f'You are now logged in as: {username}')
            welcome_email(user)
            login(request, user)
            return redirect('main:homepage')
        # if there is invalid form - display errors and refresh page and form
        else:
            for field, errors in form.errors.items():
                stripped_errors = strip_tags(errors)
                messages.error(request, f"{stripped_errors}")
            return redirect('main:register')
    # if request is GET, load the form and render register page
    else:
        form = NewUserForm
        return render(request, 'main/register.html',
                      context={'form': form})


# login view, user can log in with email or username
def login_request(request):
    if request.method == 'POST':
        form = EmailAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.clean_username()
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is None:
                user = User.objects.all().filter(email=username)
            if user is not None:
                # if data is valid, log in user and check if folder for media exists
                login(request, user)
                messages.info(request, f'You are now logged in as: {username}')
                path_temp = os.path.join(os.path.join('main', 'media', 'pics_uploaded'), '')
                path = os.path.join(BASE_DIR, '') + path_temp + username
                if not os.path.isdir(path):
                    os.mkdir(path)
                if user.is_staff:
                    messages.info(request, f'You have superuser privileges')
                return redirect('main:homepage')
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")

    # if request is GET, load the form and render log in page
    form = EmailAuthenticationForm()
    form.fields['username'].label = "Username or Email"
    return render(request,
                  'main/login.html',
                  {'form': form})


# logout view - redirects to start page after logout
def logout_request(request):
    logout(request)
    return redirect('main:start')


# account view - display all of user information in table form for easy management
def account(request):
    if request.user.is_authenticated:
        user = request.user
        notes = [x for x in Note.objects.all() if x.author.username == request.user.username]
        notes_list = [x for x in NoteList.objects.all() if x.author.username == request.user.username]
        notes_picture = [x for x in NotePicture.objects.all() if x.author.username == request.user.username]
        notes_all = [*notes, *notes_list, *notes_picture]
        notes_all.sort(key=lambda x: x.published, reverse=True)
        lengths = [len(notes), len(notes_list), len(notes_picture), len(notes_all)]
        return render(request, 'main/account.html', {'user': user,
                                                     'lengths': lengths,
                                                     'NotesAll': notes_all})

    # if user force to go to desktop view but is not logged in it redirects to start page
    else:
        return redirect('main:homepage')


# help page with information about app
def help(request):
    return render(request, 'main/help.html')


# create note page, view depends on note type
def create_note(request, note_type):
    # render page with form adequately to note type request
    if request.method == 'POST':
        if note_type == '1':
            form = NoteForm(request.POST)
        elif note_type == '2':
            form = NoteListForm(request.POST)
        elif note_type == '3':
            form = NotePictureForm(request.POST, request.FILES)
        if form.is_valid():
            if note_type != '3':
                theme_data = form.cleaned_data.get('theme')
            title_data = form.cleaned_data.get('title')
            content_data = form.cleaned_data.get('content')
            naive_datetime = datetime.now()
            time_data = make_aware(naive_datetime)
            if note_type == '1':
                obj = Note(title=title_data, content=content_data, theme=theme_data,
                           published=time_data, author=request.user)
            elif note_type == '2':
                obj = NoteList(title=title_data, content=content_data, theme=theme_data,
                               published=time_data, author=request.user)
            elif note_type == '3':
                picture_data = form.cleaned_data.get('picture')
                obj = NotePicture(title=title_data, content=content_data,
                                  published=time_data, picture=picture_data, author=request.user, )

            # if form is valid - create new note with given information and redirect to homepage
            obj.save()
            messages.info(request, f'You have created new {title_data} note')
        return redirect('main:homepage')

    # if request is GET, load the form and render create page
    if note_type == '1':
        form = NoteForm()
    if note_type == '2':
        form = NoteListForm()
    elif note_type == '3':
        form = NotePictureForm()
    return render(request,
                  'main/create.html',
                  {'form': form, 'note_type': note_type})


# update note page - similar to create page,
# but it loads information from database and pass it info form before rendering
def update_note(request, note_id, note_type, redirect_type):
    if request.method == 'POST':
        if note_type == '1':
            form = NoteForm(request.POST)
            obj = Note.objects.get(id=note_id)
        elif note_type == '2':
            form = NoteListForm(request.POST)
            obj = NoteList.objects.get(id=note_id)
        elif note_type == '3':
            form = NotePictureFormUpdate(request.POST, request.FILES or None)
            obj = NotePicture.objects.get(id=note_id)
        if form.is_valid():
            title_data = form.cleaned_data.get('title')
            content_data = form.cleaned_data.get('content')
            naive_datetime = datetime.now()
            time_data = make_aware(naive_datetime)
            obj.title = title_data
            obj.content = content_data
            obj.published = time_data
            if note_type != '3':
                theme_data = form.cleaned_data.get('theme')
                obj.theme = theme_data
            if note_type == '3':
                if form.cleaned_data.get('picture') is not None:
                    picture_data = form.cleaned_data.get('picture')
                    obj.picture = picture_data
            obj.save()

memoit/main/templates/main/account.html
{% extends "main/header.html" %}
{% block content %}
    <div class="account-header col s12">
    </div>

    {% if lengths.3 != 0 %}
        <div class="account-content col s12">
            <h3>Notes table:</h3><br>
            <table>
                <thead>
                <tr>
                    <th>Note Title</th>
                    <th class="hide-on-small-only">Note type</th>
                    <th class="hide-on-small-only">Published</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                {% for note in NotesAll %}
                    <tr>
                        <td>{{ note.title }}</td>
                        <td class="hide-on-small-only">
                            {% if note.type == 1 %} Note
                            {% elif note.type == 2 %} List Note
                            {% elif note.type == 3 %} Picture Note
                            {% endif %}
                        </td>
                        <td class="hide-on-small-only">
                            {{ note.published }}
                        </td>
                        <td class="table-action">
                            <a class='modal-trigger white-text waves-effect waves-light btn blue lighten-2 z-depth-1 account-page-hover'
                               href='#modal{{ forloop.counter }}'>Delete</a>
                            <a class="white-text waves-effect waves-light btn blue lighten-2 z-depth-1 account-page-hover"
                               href="/update/account/{{ note.type }}/{{ note.id }}">Edit</a>
                        </td>
                    </tr>

                    <div id='modal{{ forloop.counter }}' class='modal col s12 m4 offset-m2 offset-l2'>
                        <div class="modal-content ">
                            <h4>Delete</h4>
                            <p>
                                Do you really want to delete this note?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a href="/delete/account/{{ note.type }}/{{ note.id }}"
                               class="modal-close waves-effect waves-green btn-flat">Agree</a>
                        </div>
                    </div>
                {% endfor %}

                </tbody>
            </table>
        </div>
    {% else %}
        <h4>You have no notes to display</h4>
    {% endif %}


    <div class="account-other">
        <div id='modal0' class='modal col s12 m4 offset-m2 offset-l2'>
            <div class="modal-content ">
                <h4>Delete</h4>
                <p>
                    Do you really want to delete your account?
                    This will permanently delete your account along with all your memos.
                </p>
            </div>
            <div class="modal-footer">
                <a href="/delete_account" class="modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
        </div>

        <div id='modal' class='modal col s12 m4 offset-m2 offset-l2'>
            <div class="modal-content">
                <h4>Delete</h4>
                <p>
                    Do you really want to delete all your notes?
                </p>
            </div>
            <div class="modal-footer">
                <a href="/delete_all" class="modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
        </div>
    </div>

    <footer class="page-footer blue lighten-2 z-depth-3  col s12">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">{{ user.username }}</h5>
                    <p class="grey-text text-lighten-4">On this page you can manage your memos in table mode and change
                        you account details or even delete it.
                    </p>
                    <br>
                    <p>
                        <a href="/help" class="white-text text-lighten-4"><h5>Help</h5></a>
                    </p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Note summary:</h5>
                    <ul>
                        <li>Notes: {{ lengths.0 }} </li>
                        <li>List notes: {{ lengths.1 }} </li>
                        <li>Picture notes: {{ lengths.2 }} </li>
                        <li>Notes in all: {{ lengths.3 }} </li>
                    </ul>
                    <a class="modal-trigger white-text text-lighten-4 account-page-hover left"
                               href="#modal">
                           <h6>Delete all notes</h6>
                        </a>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2019 Memo IT
                <a class="modal-trigger white-text text-lighten-4 right account-page-hover" href="#modal0">
                    {% if user.is_superuser %}
                        Delete account (superuser)
                    {% else %}
                        Delete account
                    {% endif %}
                </a>
            </div>
        </div>
    </footer>
{% endblock %}

memoit/main/templates/main/create.html
{% extends "main/header.html" %}

{% block content %}

    <div class="row">
        <div style="padding-top: 50px;">
            <div class="card blue lighten-3 col s12 l6 offset-l3 m8 offset-m2 z-depth-5">
                <div class="card-content">
                    {% if note_type == '1' %}
                        <span class="card-title white-text"> Create Note</span>
                    {% elif note_type == '2' %}
                        <span class="card-title white-text"> Create List Note</span>
                    {% elif note_type == '3' %}
                        <span class="card-title white-text"> Create Picture Note</span>
                    {% endif %}
                    <div class="card-panel blue lighten-5">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="card-action">
                                <button class="btn waves-effect waves-light blue lighten-2 col s12" type="submit"
                                        name="action" style="left: 0%;">
                                    Create <i class="material-icons right">send</i></button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if note_type == '2' %}
        <script>
            $(document).ready(function () {
                // hide content for note list on loading time
                $("#id_content").parent().append("<ul id='to-do-list'></ul>");
                $("form").submit(function (event) {
                    $("#id_content").css("visibility","hidden");
                    let list_values = $.map($("#to-do-list li span"), function (elem, index) {
                        return $(elem).text();
                    }).join("|");
                    $("#id_content").val(list_values);
                    console.log(list_values);
                });
            });

            // add new entry with 'enter' key
            $('form input').keydown(function (e) {
                if (e.keyCode == 13) {
                    let inputs = $(this).parents("form").eq(0).find(":input");
                    if (inputs[inputs.index(this) + 1] != null) {
                        inputs[inputs.index(this) + 1].focus();
                    }
                    let newListItem = $("#id_content").val();
                    if (newListItem.length > 0) {
                        $("#to-do-list").append("<li class='to-do-item valign-wrapper'>" + "<span class='list-item-text left'>" + newListItem + "</span>" +
                            " <a class='waves-effect waves-light btn delete-list-item right blue lighten-2 z-depth-1'><i class='material-icons'>delete</i></a>" +
                            "</li>");
                        $("#id_content").val("");
                    }
                    e.preventDefault();
                    $(".delete-list-item").click(function () {
                        $(this).parent().remove();
                    });
                    $("#id_content").focus();
                    return false;
                }
            });
        </script>
    {% endif %}
{% endblock %}

memoit/main/templates/main/header.html
<head>
    {% load static %}
    {% load staticfiles %}
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Memo IT</title>
    <link rel="shortcut icon" href="/static/main/favicon.ico" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">

    <style>
        body {
            background-image: url("{% static '/main/images/white-waves.png'%}");;
        }
    </style>
</head>

<body>

{% include "main/includes/navbar.html" %}
{% include "main/includes/messages.html" %}
<main>
    <div class="container col s12">
        {% block content %}
        {% endblock %}
    </div>
</main>
<script>
    // initialize header
    M.AutoInit();
    $(document).ready(function () {
        $('.sidenav').sidenav();
    });
    $('textarea').each(function () {
        this.setAttribute('style', 'height:' + (this.scrollHeight) + 'px;overflow-y:hidden;');
    }).on('input', function () {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
    });

</script>
</body>

memoit/main/templates/main/update.html
{% extends "main/header.html" %}

{% block content %}

    <div class="row col s12">
    <div style="padding-top: 50px;">

    {% if theme == 1 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 blue-grey darken-1 z-depth-5">
    {% elif theme == 2 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 cyan lighten-2 z-depth-5">
    {% elif theme == 3 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 green accent-4 z-depth-5">
    {% elif theme == 4 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 amber accent-3 z-depth-5">
    {% elif theme == 5 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 purple lighten-2 z-depth-5">
    {% elif theme == 6 %}
        <div class="card col s12 l6 offset-l3 m8 offset-m2 red lighten-1 z-depth-5">
    {% endif %}





<div class="card-content">
    {% if note_type == '1' %}
        <span class="card-title white-text"> Edit Note</span>
    {% elif note_type == '2' %}
        <span class="card-title white-text"> Edit List Note</span>
    {% elif note_type == '3' %}
        <span class="card-title white-text"> Edit Picture Note</span>
    {% endif %}

    <div class="card-panel blue lighten-5">
        <form method="post" enctype="multipart/form-data" style="word-wrap: break-word;">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="card-action">
                <button class="btn waves-effect waves-light blue lighten-2 col s12" type="submit"
                        name="action" style="left: 0%;">
                    Update <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>
</div>
</div>
</div>
</div>
    {% if note_type == '2' %}
        <script>
            $("#id_content").css("visibility", "hidden");

            $(document).ready(function () {
                /* hide content for note list on loading time */
                $("#id_content").parent().append("<ul id='to-do-list'></ul>");
                $("form").submit(function (event) {
                    let list_values = $.map($("#to-do-list li span"), function (elem, index) {
                        return $(elem).text();
                    }).join("|");
                    $("#id_content").val(list_values);
                    $("#id_content").css("visibility", "visible");
                    console.log(list_values);
                });

                // for every element in list in textbox
                // parse string to list and fill note
                let input_array = $("#id_content").val().split("|");
                console.log(input_array);
                for (let i = 0; i < input_array.length; i++) {

                    $("#to-do-list").append("<li class='to-do-item valign-wrapper'>" + "<span class='list-item-text left'>" + input_array[i] + "</span>" +
                        " <a class='waves-effect waves-light btn delete-list-item right blue lighten-2 z-depth-1'><i class='material-icons'>delete</i></a>" +
                        "</li>");
                    $("#id_content").val("");

                    $(".delete-list-item").click(function () {
                        $(this).parent().remove();
                    });

                }
                $("#id_content").css("visibility", "visible");
                $("#id_content").focus();
            });
            // add new entry with 'enter' key
            $('form input').keydown(function (e) {
                if (e.keyCode == 13) {
                    let inputs = $(this).parents("form").eq(0).find(":input");
                    if (inputs[inputs.index(this) + 1] != null) {
                        inputs[inputs.index(this) + 1].focus();
                    }
                    let newListItem = $("#id_content").val();
                    if (newListItem.length > 0) {
                        $("#to-do-list").append("<li class='to-do-item valign-wrapper'>" + "<span class='list-item-text left'>" + newListItem + "</span>" +
                            " <a class='waves-effect waves-light btn delete-list-item right blue lighten-2 z-depth-1'><i class='material-icons'>delete</i></a>" +
                            "</li>");
                        $("#id_content").val("");
                    }
                    e.preventDefault();
                    $(".delete-list-item").click(function () {
                        $(this).parent().remove();
                    });
                    $("#id_content").focus();
                    return false;
                }
            });
        </script>
    {% endif %}

    {% if note_type == '3' %}
        <script>
            $("label[for='id_picture']").append("<br>");
        </script>

    {% endif %}
{% endblock %}